#!/usr/bin/bash

# staffing
git pull origin master

cd shotglass2/
git pull origin master

cd ../feedme/
git pull origin master
cd rfeed/
git pull origin master
cd ../../

cd ical/
git pull origin master


cd ../
echo 'All Done'


